package main

// Instruction decoding table
Instructions := [256]Instruction {
	0x00 = {mnemonic = "brk", handler = brk},
	0x01 = {handler = not_implemented},
	0x02 = {handler = not_implemented},
	0x03 = {handler = not_implemented},
	0x04 = {handler = not_implemented},
	0x05 = {handler = not_implemented},
	0x06 = {mnemonic = "asl zpg", handler = asl_zpg},
	0x07 = {handler = not_implemented},
	0x08 = {handler = not_implemented},
	0x09 = {handler = not_implemented},
	0x0A = {mnemonic = "asl A", handler = asl_a},
	0x0B = {handler = not_implemented},
	0x0C = {handler = not_implemented},
	0x0D = {handler = not_implemented},
	0x0E = {mnemonic = "asl abs", handler = asl_abs},
	0x0F = {handler = not_implemented},
	0x10 = {mnemonic = "bpl", handler = bpl},
	0x11 = {handler = not_implemented},
	0x12 = {handler = not_implemented},
	0x13 = {handler = not_implemented},
	0x14 = {handler = not_implemented},
	0x15 = {handler = not_implemented},
	0x16 = {mnemonic = "asl zpg,X", handler = asl_zpgx},
	0x17 = {handler = not_implemented},
	0x18 = {mnemonic = "clc", handler = clc},
	0x19 = {handler = not_implemented},
	0x1A = {handler = not_implemented},
	0x1B = {handler = not_implemented},
	0x1C = {handler = not_implemented},
	0x1D = {handler = not_implemented},
	0x1E = {mnemonic = "asl abs,X", handler = asl_absx},
	0x1F = {handler = not_implemented},
	0x20 = {handler = not_implemented},
	0x21 = {mnemonic = "and ind,X", handler = and_indx},
	0x22 = {handler = not_implemented},
	0x23 = {handler = not_implemented},
	0x24 = {mnemonic = "bit zpg", handler = bit_zpg},
	0x25 = {mnemonic = "and zpg", handler = and_zpg},
	0x26 = {handler = not_implemented},
	0x27 = {handler = not_implemented},
	0x28 = {handler = not_implemented},
	0x29 = {mnemonic = "and #", handler = and_imm},
	0x2A = {handler = not_implemented},
	0x2B = {handler = not_implemented},
	0x2C = {mnemonic = "bit abs", handler = bit_abs},
	0x2D = {mnemonic = "and abs", handler = and_abs},
	0x2E = {handler = not_implemented},
	0x2F = {handler = not_implemented},
	0x30 = {mnemonic = "bmi", handler = bmi},
	0x31 = {mnemonic = "and ind,Y", handler = and_indy},
	0x32 = {handler = not_implemented},
	0x33 = {handler = not_implemented},
	0x34 = {handler = not_implemented},
	0x35 = {mnemonic = "and zpg,X", handler = and_zpgx},
	0x36 = {handler = not_implemented},
	0x37 = {handler = not_implemented},
	0x38 = {handler = not_implemented},
	0x39 = {mnemonic = "and abs,Y", handler = and_absy},
	0x3A = {handler = not_implemented},
	0x3B = {handler = not_implemented},
	0x3C = {handler = not_implemented},
	0x3D = {mnemonic = "and abs,X", handler = and_absx},
	0x3E = {handler = not_implemented},
	0x3F = {handler = not_implemented},
	0x40 = {handler = not_implemented},
	0x41 = {mnemonic = "eor ind,X", handler = eor_indx},
	0x42 = {handler = not_implemented},
	0x43 = {handler = not_implemented},
	0x44 = {handler = not_implemented},
	0x45 = {mnemonic = "eor zpg", handler = eor_zpg},
	0x46 = {handler = not_implemented},
	0x47 = {handler = not_implemented},
	0x48 = {handler = not_implemented},
	0x49 = {mnemonic = "eor #", handler = eor_imm},
	0x4A = {handler = not_implemented},
	0x4B = {handler = not_implemented},
	0x4C = {mnemonic = "jmp abs", handler = jmp_abs},
	0x4D = {mnemonic = "eor abs", handler = eor_abs},
	0x4E = {handler = not_implemented},
	0x4F = {handler = not_implemented},
	0x50 = {mnemonic = "bvc", handler = bvc},
	0x51 = {mnemonic = "eor ind,Y", handler = eor_indy},
	0x52 = {handler = not_implemented},
	0x53 = {handler = not_implemented},
	0x54 = {handler = not_implemented},
	0x55 = {mnemonic = "eor zpg,X", handler = eor_zpgx},
	0x56 = {handler = not_implemented},
	0x57 = {handler = not_implemented},
	0x58 = {mnemonic = "cli", handler = cli},
	0x59 = {mnemonic = "eor abs,Y", handler = eor_absy},
	0x5A = {handler = not_implemented},
	0x5B = {handler = not_implemented},
	0x5C = {handler = not_implemented},
	0x5D = {mnemonic = "eor abs,X", handler = eor_absx},
	0x5E = {handler = not_implemented},
	0x5F = {handler = not_implemented},
	0x60 = {handler = not_implemented},
	0x61 = {mnemonic = "adc ind,X", handler = adc_indx},
	0x62 = {handler = not_implemented},
	0x63 = {handler = not_implemented},
	0x64 = {handler = not_implemented},
	0x65 = {mnemonic = "adc zpg", handler = adc_zpg},
	0x66 = {handler = not_implemented},
	0x67 = {handler = not_implemented},
	0x68 = {handler = not_implemented},
	0x69 = {mnemonic = "adc #", handler = adc_imm},
	0x6A = {handler = not_implemented},
	0x6B = {handler = not_implemented},
	0x6C = {mnemonic = "jmp ind", handler = jmp_ind},
	0x6D = {mnemonic = "adc abs", handler = adc_abs},
	0x6E = {handler = not_implemented},
	0x6F = {handler = not_implemented},
	0x70 = {mnemonic = "bvs", handler = bvs},
	0x71 = {mnemonic = "adc ind,Y", handler = adc_indy},
	0x72 = {handler = not_implemented},
	0x73 = {handler = not_implemented},
	0x74 = {handler = not_implemented},
	0x75 = {mnemonic = "adc zpg,X", handler = adc_zpgx},
	0x76 = {handler = not_implemented},
	0x77 = {handler = not_implemented},
	0x78 = {handler = not_implemented},
	0x79 = {mnemonic = "adc abs,Y", handler = adc_absy},
	0x7A = {handler = not_implemented},
	0x7B = {handler = not_implemented},
	0x7C = {handler = not_implemented},
	0x7D = {mnemonic = "adc abs,X", handler = adc_absx},
	0x7E = {handler = not_implemented},
	0x7F = {handler = not_implemented},
	0x80 = {handler = not_implemented},
	0x81 = {handler = not_implemented},
	0x82 = {handler = not_implemented},
	0x83 = {handler = not_implemented},
	0x84 = {handler = not_implemented},
	0x85 = {handler = not_implemented},
	0x86 = {handler = not_implemented},
	0x87 = {handler = not_implemented},
	0x88 = {mnemonic = "dey", handler = dey},
	0x89 = {handler = not_implemented},
	0x8A = {handler = not_implemented},
	0x8B = {handler = not_implemented},
	0x8C = {handler = not_implemented},
	0x8D = {handler = not_implemented},
	0x8E = {handler = not_implemented},
	0x8F = {handler = not_implemented},
	0x90 = {mnemonic = "bcc", handler = bcc},
	0x91 = {handler = not_implemented},
	0x92 = {handler = not_implemented},
	0x93 = {handler = not_implemented},
	0x94 = {handler = not_implemented},
	0x95 = {handler = not_implemented},
	0x96 = {handler = not_implemented},
	0x97 = {handler = not_implemented},
	0x98 = {handler = not_implemented},
	0x99 = {handler = not_implemented},
	0x9A = {handler = not_implemented},
	0x9B = {handler = not_implemented},
	0x9C = {handler = not_implemented},
	0x9D = {handler = not_implemented},
	0x9E = {handler = not_implemented},
	0x9F = {handler = not_implemented},
	0xA0 = {handler = not_implemented},
	0xA1 = {handler = not_implemented},
	0xA2 = {handler = not_implemented},
	0xA3 = {handler = not_implemented},
	0xA4 = {handler = not_implemented},
	0xA5 = {handler = not_implemented},
	0xA6 = {handler = not_implemented},
	0xA7 = {handler = not_implemented},
	0xA8 = {handler = not_implemented},
	0xA9 = {handler = not_implemented},
	0xAA = {handler = not_implemented},
	0xAB = {handler = not_implemented},
	0xAC = {handler = not_implemented},
	0xAD = {handler = not_implemented},
	0xAE = {handler = not_implemented},
	0xAF = {handler = not_implemented},
	0xB0 = {mnemonic = "bcs", handler = bcs},
	0xB1 = {handler = not_implemented},
	0xB2 = {handler = not_implemented},
	0xB3 = {handler = not_implemented},
	0xB4 = {handler = not_implemented},
	0xB5 = {handler = not_implemented},
	0xB6 = {handler = not_implemented},
	0xB7 = {handler = not_implemented},
	0xB8 = {mnemonic = "clv", handler = clv},
	0xB9 = {handler = not_implemented},
	0xBA = {handler = not_implemented},
	0xBB = {handler = not_implemented},
	0xBC = {handler = not_implemented},
	0xBD = {handler = not_implemented},
	0xBE = {handler = not_implemented},
	0xBF = {handler = not_implemented},
	0xC0 = {mnemonic = "cpy imm", handler = cpy_imm},
	0xC1 = {mnemonic = "cmp ind,X", handler = cmp_indx},
	0xC2 = {handler = not_implemented},
	0xC3 = {handler = not_implemented},
	0xC4 = {mnemonic = "cpy zpg", handler = cpy_zpg},
	0xC5 = {mnemonic = "cmp zpg", handler = cmp_zpg},
	0xC6 = {mnemonic = "dec zpg", handler = dec_zpg},
	0xC7 = {handler = not_implemented},
	0xC8 = {mnemonic = "iny", handler = iny},
	0xC9 = {mnemonic = "cmp #", handler = cmp_imm},
	0xCA = {mnemonic = "dex", handler = dex},
	0xCB = {handler = not_implemented},
	0xCC = {mnemonic = "cpy abs", handler = cpy_abs},
	0xCD = {mnemonic = "cmp abs", handler = cmp_abs},
	0xCE = {mnemonic = "dec abs", handler = dec_abs},
	0xCF = {handler = not_implemented},
	0xD0 = {mnemonic = "bne", handler = bne},
	0xD1 = {mnemonic = "cmp ind,Y", handler = cmp_indy},
	0xD2 = {handler = not_implemented},
	0xD3 = {handler = not_implemented},
	0xD4 = {handler = not_implemented},
	0xD5 = {mnemonic = "cmp zpg,X", handler = cmp_zpgx},
	0xD6 = {mnemonic = "dec zpg,X", handler = dec_zpgx},
	0xD7 = {handler = not_implemented},
	0xD8 = {mnemonic = "cld", handler = cld},
	0xD9 = {mnemonic = "cmp abs,Y", handler = cmp_absy},
	0xDA = {handler = not_implemented},
	0xDB = {handler = not_implemented},
	0xDC = {handler = not_implemented},
	0xDD = {mnemonic = "cmp abs,X", handler = cmp_absx},
	0xDE = {mnemonic = "dec abs,X", handler = dec_absx},
	0xDF = {handler = not_implemented},
	0xE0 = {mnemonic = "cpx imm", handler = cpx_imm},
	0xE1 = {handler = not_implemented},
	0xE2 = {handler = not_implemented},
	0xE3 = {handler = not_implemented},
	0xE4 = {mnemonic = "cpx zpg", handler = cpx_zpg},
	0xE5 = {handler = not_implemented},
	0xE6 = {mnemonic = "inc zpg", handler = inc_zpg},
	0xE7 = {handler = not_implemented},
	0xE8 = {mnemonic = "inx", handler = inx},
	0xE9 = {handler = not_implemented},
	0xEA = {handler = not_implemented},
	0xEB = {handler = not_implemented},
	0xEC = {mnemonic = "cpx abs", handler = cpx_abs},
	0xED = {handler = not_implemented},
	0xEE = {mnemonic = "inc abs", handler = inc_abs},
	0xEF = {handler = not_implemented},
	0xF0 = {mnemonic = "beq", handler = beq},
	0xF1 = {handler = not_implemented},
	0xF2 = {handler = not_implemented},
	0xF3 = {handler = not_implemented},
	0xF4 = {handler = not_implemented},
	0xF5 = {handler = not_implemented},
	0xF6 = {mnemonic = "inc zpg,X", handler = inc_zpgx},
	0xF7 = {handler = not_implemented},
	0xF8 = {handler = not_implemented},
	0xF9 = {handler = not_implemented},
	0xFA = {handler = not_implemented},
	0xFB = {handler = not_implemented},
	0xFC = {handler = not_implemented},
	0xFD = {handler = not_implemented},
	0xFE = {mnemonic = "inc abs,X", handler = inc_absx},
	0xFF = {handler = not_implemented},
}