package main

// Instruction decoding table
Instructions := [256]Instruction {
	0x00 = {mnemonic = "brk",									handler = brk},
	0x01 = {mnemonic = "ora ind,X",	format = "ora ($%02X,X)",	handler = ora_indx},
	0x02 = {mnemonic = "jam",									handler = jam},
	0x03 = {mnemonic = "slo ind,X",	format = "slo ($%02X,X)",	handler = slo_indx},
	0x04 = {mnemonic = "nop zpg",	format = "nop <$%02X",		handler = nop_zpg},
	0x05 = {mnemonic = "ora zpg",	format = "ora <$%02X",		handler = ora_zpg},
	0x06 = {mnemonic = "asl zpg",	format = "asl <$%02X",		handler = asl_zpg},
	0x07 = {mnemonic = "slo zpg",	format = "slo <$%02X",		handler = slo_zpg},
	0x08 = {mnemonic = "php",									handler = php},
	0x09 = {mnemonic = "ora #",		format = "ora #$%02X",		handler = ora_imm},
	0x0A = {mnemonic = "asl A",									handler = asl_a},
	0x0B = {mnemonic = "anc",		format = "anc #$%02X",		handler = anc},
	0x0C = {mnemonic = "nop abs",	format = "nop $%02X%02X",	handler = nop_abs},
	0x0D = {mnemonic = "ora abs",	format = "ora $%02X%02X",	handler = ora_abs},
	0x0E = {mnemonic = "asl abs",	format = "asl $%02X%02X",	handler = asl_abs},
	0x0F = {mnemonic = "slo abs",	format = "slo $%02X%02X",	handler = slo_abs},
	0x10 = {mnemonic = "bpl",		format = "bpl $%04X",		handler = bpl},
	0x11 = {mnemonic = "ora ind,Y",	format = "ora ($%02X),Y",	handler = ora_indy},
	0x12 = {mnemonic = "jam",									handler = jam},
	0x13 = {mnemonic = "slo ind,Y",	format = "slo ($%02X),Y",	handler = slo_indy},
	0x14 = {mnemonic = "nop zpg,X",	format = "nop <$%02X,X",	handler = nop_zpgx},
	0x15 = {mnemonic = "ora zpg,X",	format = "ora <$%02X,X",	handler = ora_zpgx},
	0x16 = {mnemonic = "asl zpg,X",	format = "asl <$%02X,X",	handler = asl_zpgx},
	0x17 = {mnemonic = "slo zpg,X",	format = "slo <$%02X,X",	handler = slo_zpgx},
	0x18 = {mnemonic = "clc",									handler = clc},
	0x19 = {mnemonic = "ora abs,Y",	format = "ora $%02X%02X,Y",	handler = ora_absy},
	0x1A = {mnemonic = "nop imp",								handler = nop_implied},
	0x1B = {mnemonic = "slo abs,Y",	format = "slo $%02X%02X,Y",	handler = slo_absy},
	0x1C = {mnemonic = "nop abs,X",	format = "nop $%02X%02X,X",	handler = nop_absx},
	0x1D = {mnemonic = "ora abs,X",	format = "ora $%02X%02X,X",	handler = ora_absx},
	0x1E = {mnemonic = "asl abs,X",	format = "asl $%02X%02X,X",	handler = asl_absx},
	0x1F = {mnemonic = "slo abs,X",	format = "slo $%02X%02X,X",	handler = slo_absx},
	0x20 = {mnemonic = "jsr",		format = "jsr $%02X%02X",	handler = jsr},
	0x21 = {mnemonic = "and ind,X",	format = "and ($%02X,X)",	handler = and_indx},
	0x22 = {mnemonic = "jam",									handler = jam},
	0x23 = {mnemonic = "rla ind,X",	format = "rla ($%02X,X)",	handler = rla_indx},
	0x24 = {mnemonic = "bit zpg",	format = "bit <$%02X",		handler = bit_zpg},
	0x25 = {mnemonic = "and zpg",	format = "and <$%02X",		handler = and_zpg},
	0x26 = {mnemonic = "rol zpg",	format = "rol <$%02X",		handler = rol_zpg},
	0x27 = {mnemonic = "rla zpg",	format = "rla <$%02X",		handler = rla_zpg},
	0x28 = {mnemonic = "plp",									handler = plp},
	0x29 = {mnemonic = "and #",		format = "and #$%02X",		handler = and_imm},
	0x2A = {mnemonic = "rol A",									handler = rol_a},
	0x2B = {mnemonic = "anc",		format = "anc #$%02X",		handler = anc},
	0x2C = {mnemonic = "bit abs",	format = "bit $%02X%02X",	handler = bit_abs},
	0x2D = {mnemonic = "and abs",	format = "and $%02X%02X",	handler = and_abs},
	0x2E = {mnemonic = "rol abs",	format = "rol $%02X%02X",	handler = rol_abs},
	0x2F = {mnemonic = "rla abs",	format = "rla $%02X%02X",	handler = rla_abs},
	0x30 = {mnemonic = "bmi",		format = "bmi $%04X",		handler = bmi},
	0x31 = {mnemonic = "and ind,Y",	format = "and ($%02X),Y",	handler = and_indy},
	0x32 = {mnemonic = "jam",									handler = jam},
	0x33 = {mnemonic = "rla ind,Y",	format = "rla ($%02X),Y",	handler = rla_indy},
	0x34 = {mnemonic = "nop zpg,X",	format = "nop <$%02X,X",	handler = nop_zpgx},
	0x35 = {mnemonic = "and zpg,X",	format = "and <$%02X,X",	handler = and_zpgx},
	0x36 = {mnemonic = "rol zpg,X",	format = "rol <$%02X,X",	handler = rol_zpgx},
	0x37 = {mnemonic = "rla zpg,X",	format = "rla <$%02X,X",	handler = rla_zpgx},
	0x38 = {mnemonic = "sec",									handler = sec},
	0x39 = {mnemonic = "and abs,Y",	format = "and $%02X%02X,Y",	handler = and_absy},
	0x3A = {mnemonic = "nop imp",								handler = nop_implied},
	0x3B = {mnemonic = "rla abs,Y",	format = "rla $%02X%02X,Y",	handler = rla_absy},
	0x3C = {mnemonic = "nop abs,X",	format = "nop $%02X%02X,X",	handler = nop_absx},
	0x3D = {mnemonic = "and abs,X",	format = "and $%02X%02X,X",	handler = and_absx},
	0x3E = {mnemonic = "rol abs,X",	format = "rol $%02X%02X,X",	handler = rol_absx},
	0x3F = {mnemonic = "rla abs,X",	format = "rla $%02X%02X,X",	handler = rla_absx},
	0x40 = {mnemonic = "rti",									handler = rti},
	0x41 = {mnemonic = "eor ind,X",	format = "eor ($%02X,X)",	handler = eor_indx},
	0x42 = {mnemonic = "jam",									handler = jam},
	0x43 = {mnemonic = "sre ind,X",	format = "sre ($%02X,X)",	handler = sre_indx},
	0x44 = {mnemonic = "nop zpg",	format = "nop <$%02X",		handler = nop_zpg},
	0x45 = {mnemonic = "eor zpg",	format = "eor <$%02X",		handler = eor_zpg},
	0x46 = {mnemonic = "lsr zpg",	format = "lsr <$%02X",		handler = lsr_zpg},
	0x47 = {mnemonic = "sre zpg",	format = "sre <$%02X",		handler = sre_zpg},
	0x48 = {mnemonic = "pha",									handler = pha},
	0x49 = {mnemonic = "eor #",		format = "eor #$%02X",		handler = eor_imm},
	0x4A = {mnemonic = "lsr A",									handler = lsr_a},
	0x4B = {mnemonic = "alr",		format = "alr #$%02X",		handler = alr},
	0x4C = {mnemonic = "jmp abs",	format = "jmp $%02X%02X",	handler = jmp_abs},
	0x4D = {mnemonic = "eor abs",	format = "eor $%02X%02X",	handler = eor_abs},
	0x4E = {mnemonic = "lsr abs",	format = "lsr $%02X%02X",	handler = lsr_abs},
	0x4F = {mnemonic = "sre abs",	format = "sre $%02X%02X",	handler = sre_abs},
	0x50 = {mnemonic = "bvc",		format = "bvc $%04X",		handler = bvc},
	0x51 = {mnemonic = "eor ind,Y",	format = "eor ($%02X),Y",	handler = eor_indy},
	0x52 = {mnemonic = "jam",									handler = jam},
	0x53 = {mnemonic = "sre ind,Y",	format = "sre ($%02X),Y",	handler = sre_indy},
	0x54 = {mnemonic = "nop zpg,X",	format = "nop <$%02X,X",	handler = nop_zpgx},
	0x55 = {mnemonic = "eor zpg,X",	format = "eor <$%02X,X",	handler = eor_zpgx},
	0x56 = {mnemonic = "lsr zpg,X",	format = "lsr <$%02X,X",	handler = lsr_zpgx},
	0x57 = {mnemonic = "sre zpg,X",	format = "sre <$%02X,X",	handler = sre_zpgx},
	0x58 = {mnemonic = "cli",									handler = cli},
	0x59 = {mnemonic = "eor abs,Y",	format = "eor $%02X%02X,Y",	handler = eor_absy},
	0x5A = {mnemonic = "nop imp",								handler = nop_implied},
	0x5B = {mnemonic = "sre abs,Y",	format = "sre $%02X%02X,Y",	handler = sre_absy},
	0x5C = {mnemonic = "nop abs,X",	format = "nop $%02X%02X,X",	handler = nop_absx},
	0x5D = {mnemonic = "eor abs,X",	format = "eor $%02X%02X,X",	handler = eor_absx},
	0x5E = {mnemonic = "lsr abs,X",	format = "lsr $%02X%02X,X",	handler = lsr_absx},
	0x5F = {mnemonic = "sre abs,X",	format = "sre $%02X%02X,X",	handler = sre_absx},
	0x60 = {mnemonic = "rts",									handler = rts},
	0x61 = {mnemonic = "adc ind,X",	format = "adc ($%02X,X)",	handler = adc_indx},
	0x62 = {mnemonic = "jam",									handler = jam},
	0x63 = {mnemonic = "rra ind,X",	format = "rra ($%02X,X)",	handler = rra_indx},
	0x64 = {mnemonic = "nop zpg",	format = "nop <$%02X",		handler = nop_zpg},
	0x65 = {mnemonic = "adc zpg",	format = "adc <$%02X",		handler = adc_zpg},
	0x66 = {mnemonic = "ror zpg",	format = "ror <$%02X",		handler = ror_zpg},
	0x67 = {mnemonic = "rra zpg",	format = "rra <$%02X",		handler = rra_zpg},
	0x68 = {mnemonic = "pla",									handler = pla},
	0x69 = {mnemonic = "adc #",		format = "adc #$%02X",		handler = adc_imm},
	0x6A = {mnemonic = "ror A",									handler = ror_a},
	0x6B = {mnemonic = "arr",		format = "arr #$%02X",		handler = arr},
	0x6C = {mnemonic = "jmp ind",	format = "jmp ($%02X%02X)",	handler = jmp_ind},
	0x6D = {mnemonic = "adc abs",	format = "adc $%02X%02X",	handler = adc_abs},
	0x6E = {mnemonic = "ror abs",	format = "ror $%02X%02X",	handler = ror_abs},
	0x6F = {mnemonic = "rra abs",	format = "rra $%02X%02X",	handler = rra_abs},
	0x70 = {mnemonic = "bvs",		format = "bvs $%04X",		handler = bvs},
	0x71 = {mnemonic = "adc ind,Y",	format = "adc ($%02X),Y",	handler = adc_indy},
	0x72 = {mnemonic = "jam",									handler = jam},
	0x73 = {mnemonic = "rra ind,Y",	format = "rra ($%02X),Y",	handler = rra_indy},
	0x74 = {mnemonic = "nop zpg,X",	format = "nop <$%02X,X",	handler = nop_zpgx},
	0x75 = {mnemonic = "adc zpg,X",	format = "adc <$%02X,X",	handler = adc_zpgx},
	0x76 = {mnemonic = "ror zpg,X",	format = "ror <$%02X,X",	handler = ror_zpgx},
	0x77 = {mnemonic = "rra zpg,X",	format = "rra <$%02X,X",	handler = rra_zpgx},
	0x78 = {mnemonic = "sei",									handler = sei},
	0x79 = {mnemonic = "adc abs,Y",	format = "adc $%02X%02X,Y",	handler = adc_absy},
	0x7A = {mnemonic = "nop imp",								handler = nop_implied},
	0x7B = {mnemonic = "rra abs,Y",	format = "rra $%02X%02X,Y",	handler = rra_absy},
	0x7C = {mnemonic = "nop abs,X",	format = "nop $%02X%02X,X",	handler = nop_absx},
	0x7D = {mnemonic = "adc abs,X",	format = "adc $%02X%02X,X",	handler = adc_absx},
	0x7E = {mnemonic = "ror abs,X",	format = "ror $%02X%02X,X",	handler = ror_absx},
	0x7F = {mnemonic = "rra abs,X",	format = "rra $%02X%02X,X",	handler = rra_absx},
	0x80 = {mnemonic = "nop #",		format = "nop #$%02X",		handler = nop_imm},
	0x81 = {mnemonic = "sta ind,X",	format = "sta ($%02X,X)",	handler = sta_indx},
	0x82 = {mnemonic = "nop #",		format = "nop #$%02X",		handler = nop_imm},
	0x83 = {mnemonic = "sax ind,X",	format = "sax ($%02X,X)",	handler = sax_indx},
	0x84 = {mnemonic = "sty zpg",	format = "sty <$%02X",		handler = sty_zpg},
	0x85 = {mnemonic = "sta zpg",	format = "sta <$%02X",		handler = sta_zpg},
	0x86 = {mnemonic = "stx zpg",	format = "stx <$%02X",		handler = stx_zpg},
	0x87 = {mnemonic = "sax zpg",	format = "sax <$%02X",		handler = sax_zpg},
	0x88 = {mnemonic = "dey",									handler = dey},
	0x89 = {mnemonic = "nop #",		format = "nop #$%02X",		handler = nop_imm},
	0x8A = {mnemonic = "txa",									handler = txa},
	0x8B = {mnemonic = "ane",		format = "ane #$%02X",		handler = ane},
	0x8C = {mnemonic = "sty abs",	format = "sty $%02X%02X",	handler = sty_abs},
	0x8D = {mnemonic = "sta abs",	format = "sta $%02X%02X",	handler = sta_abs},
	0x8E = {mnemonic = "stx abs",	format = "stx $%02X%02X",	handler = stx_abs},
	0x8F = {mnemonic = "sax abs",	format = "sax $%02X%02X",	handler = sax_abs},
	0x90 = {mnemonic = "bcc",		format = "bcc $%04X",		handler = bcc},
	0x91 = {mnemonic = "sta ind,Y",	format = "sta ($%02X),Y",	handler = sta_indy},
	0x92 = {mnemonic = "jam",									handler = jam},
	0x93 = {mnemonic = "sha ind,Y",	format = "sha ($%02X),Y",	handler = sha_indy},
	0x94 = {mnemonic = "sty zpg,X",	format = "sty <$%02X,X",	handler = sty_zpgx},
	0x95 = {mnemonic = "sta zpg,X",	format = "sta <$%02X,X",	handler = sta_zpgx},
	0x96 = {mnemonic = "stx zpg,Y",	format = "stx <$%02X,Y",	handler = stx_zpgy},
	0x97 = {mnemonic = "sax zpg,Y",	format = "sax <$%02X,Y",	handler = sax_zpgy},
	0x98 = {mnemonic = "tya",									handler = tya},
	0x99 = {mnemonic = "sta abs,Y",	format = "sta $%02X%02X,Y",	handler = sta_absy},
	0x9A = {mnemonic = "txs",									handler = txs},
	0x9B = {mnemonic = "tas abs,Y",	format = "tas $%02X%02X,Y",	handler = tas},
	0x9C = {mnemonic = "shy abs,X",	format = "shy $%02X%02X,X",	handler = shy},
	0x9D = {mnemonic = "sta abs,X",	format = "sta $%02X%02X,X",	handler = sta_absx},
	0x9E = {mnemonic = "shx abs,Y",	format = "shx $%02X%02X,Y",	handler = shx},
	0x9F = {mnemonic = "sha abs,Y",	format = "sha $%02X%02X,Y",	handler = sha_absy},
	0xA0 = {mnemonic = "ldy #",		format = "ldy #$%02X",		handler = ldy_imm},
	0xA1 = {mnemonic = "lda ind,X",	format = "lda ($%02X,X)",	handler = lda_indx},
	0xA2 = {mnemonic = "ldx #",		format = "ldx #$%02X",		handler = ldx_imm},
	0xA3 = {mnemonic = "lax ind,X",	format = "lax ($%02X,X)",	handler = lax_indx},
	0xA4 = {mnemonic = "ldy zpg",	format = "ldy <$%02X",		handler = ldy_zpg},
	0xA5 = {mnemonic = "lda zpg",	format = "lda <$%02X",		handler = lda_zpg},
	0xA6 = {mnemonic = "ldx zpg",	format = "ldx <$%02X",		handler = ldx_zpg},
	0xA7 = {mnemonic = "lax zpg",	format = "lax <$%02X",		handler = lax_zpg},
	0xA8 = {mnemonic = "tay",									handler = tay},
	0xA9 = {mnemonic = "lda #",		format = "lda #$%02X",		handler = lda_imm},
	0xAA = {mnemonic = "tax",									handler = tax},
	0xAB = {mnemonic = "lxa #",		format = "lxa #$%02X",		handler = lxa},
	0xAC = {mnemonic = "ldy abs",	format = "ldy $%02X%02X",	handler = ldy_abs},
	0xAD = {mnemonic = "lda abs",	format = "lda $%02X%02X",	handler = lda_abs},
	0xAE = {mnemonic = "ldx abs",	format = "ldx $%02X%02X",	handler = ldx_abs},
	0xAF = {mnemonic = "lax abs",	format = "lax $%02X%02X",	handler = lax_abs},
	0xB0 = {mnemonic = "bcs",		format = "bcs $%04X",		handler = bcs},
	0xB1 = {mnemonic = "lda ind,Y",	format = "lda ($%02X),Y",	handler = lda_indy},
	0xB2 = {mnemonic = "jam",									handler = jam},
	0xB3 = {mnemonic = "lax ind,Y",	format = "lax ($%02X),Y",	handler = lax_indy},
	0xB4 = {mnemonic = "ldy zpg,X",	format = "ldy <$%02X,X",	handler = ldy_zpgx},
	0xB5 = {mnemonic = "lda zpg,X",	format = "lda <$%02X,X",	handler = lda_zpgx},
	0xB6 = {mnemonic = "ldx zpg,Y",	format = "ldx <$%02X,Y",	handler = ldx_zpgy},
	0xB7 = {mnemonic = "lax zpg,Y",	format = "lax <$%02X,Y",	handler = lax_zpgy},
	0xB8 = {mnemonic = "clv",									handler = clv},
	0xB9 = {mnemonic = "lda abs,Y",	format = "lda $%02X%02X,Y",	handler = lda_absy},
	0xBA = {mnemonic = "tsx",									handler = tsx},
	0xBB = {mnemonic = "las abs,Y",	format = "las $%02X%02X,Y",	handler = las_absy},
	0xBC = {mnemonic = "ldy abs,X",	format = "ldy $%02X%02X,X",	handler = ldy_absx},
	0xBD = {mnemonic = "lda abs,X",	format = "lda $%02X%02X,X",	handler = lda_absx},
	0xBE = {mnemonic = "ldx abs,Y",	format = "ldx $%02X%02X,Y",	handler = ldx_absy},
	0xBF = {mnemonic = "lax abs,Y",	format = "lax $%02X%02X,Y",	handler = lax_absy},
	0xC0 = {mnemonic = "cpy #",		format = "cpy #$%02X",		handler = cpy_imm},
	0xC1 = {mnemonic = "cmp ind,X",	format = "cmp ($%02X,X)",	handler = cmp_indx},
	0xC2 = {mnemonic = "nop #",		format = "nop #$%02X",		handler = nop_imm},
	0xC3 = {mnemonic = "dcp ind,X",	format = "dcp ($%02X,X)",	handler = dcp_indx},
	0xC4 = {mnemonic = "cpy zpg",	format = "cpy <$%02X",		handler = cpy_zpg},
	0xC5 = {mnemonic = "cmp zpg",	format = "cmp <$%02X",		handler = cmp_zpg},
	0xC6 = {mnemonic = "dec zpg",	format = "dec <$%02X",		handler = dec_zpg},
	0xC7 = {mnemonic = "dcp zpg",	format = "dcp <$%02X",		handler = dcp_zpg},
	0xC8 = {mnemonic = "iny",									handler = iny},
	0xC9 = {mnemonic = "cmp #",		format = "cmp #$%02X",		handler = cmp_imm},
	0xCA = {mnemonic = "dex",									handler = dex},
	0xCB = {mnemonic = "sbx #",		format = "sbx #$%02X",		handler = sbx},
	0xCC = {mnemonic = "cpy abs",	format = "cpy $%02X%02X",	handler = cpy_abs},
	0xCD = {mnemonic = "cmp abs",	format = "cmp $%02X%02X",	handler = cmp_abs},
	0xCE = {mnemonic = "dec abs",	format = "dec $%02X%02X",	handler = dec_abs},
	0xCF = {mnemonic = "dcp abs",	format = "dcp $%02X%02X",	handler = dcp_abs},
	0xD0 = {mnemonic = "bne",		format = "bne $%04X",		handler = bne},
	0xD1 = {mnemonic = "cmp ind,Y",	format = "cmp ($%02X),Y",	handler = cmp_indy},
	0xD2 = {mnemonic = "jam",									handler = jam},
	0xD3 = {mnemonic = "dcp ind,Y",	format = "dcp ($%02X),Y",	handler = dcp_indy},
	0xD4 = {mnemonic = "nop zpg,X",	format = "nop <$%02X,X",	handler = nop_zpgx},
	0xD5 = {mnemonic = "cmp zpg,X",	format = "cmp <$%02X,X",	handler = cmp_zpgx},
	0xD6 = {mnemonic = "dec zpg,X",	format = "dec <$%02X,X",	handler = dec_zpgx},
	0xD7 = {mnemonic = "dcp zpg,X",	format = "dcp <$%02X,X",	handler = dcp_zpgx},
	0xD8 = {mnemonic = "cld",									handler = cld},
	0xD9 = {mnemonic = "cmp abs,Y",	format = "cmp $%02X%02X,Y",	handler = cmp_absy},
	0xDA = {mnemonic = "nop imp",								handler = nop_implied},
	0xDB = {mnemonic = "dcp abs,Y",	format = "dcp $%02X%02X,Y",	handler = dcp_absy},
	0xDC = {mnemonic = "nop abs,X",	format = "nop $%02X%02X,X",	handler = nop_absx},
	0xDD = {mnemonic = "cmp abs,X",	format = "cmp $%02X%02X,X",	handler = cmp_absx},
	0xDE = {mnemonic = "dec abs,X",	format = "dec $%02X%02X,X",	handler = dec_absx},
	0xDF = {mnemonic = "dcp abs,X",	format = "dcp $%02X%02X,X",	handler = dcp_absx},
	0xE0 = {mnemonic = "cpx #",		format = "cpx #$%02X",		handler = cpx_imm},
	0xE1 = {mnemonic = "sbc ind,X",	format = "sbc ($%02X,X)",	handler = sbc_indx},
	0xE2 = {mnemonic = "nop #",		format = "nop #$%02X",		handler = nop_imm},
	0xE3 = {mnemonic = "isc ind,X",	format = "isc ($%02X,X)",	handler = isc_indx},
	0xE4 = {mnemonic = "cpx zpg",	format = "cpx <$%02X",		handler = cpx_zpg},
	0xE5 = {mnemonic = "sbc zpg",	format = "sbc <$%02X",		handler = sbc_zpg},
	0xE6 = {mnemonic = "inc zpg",	format = "inc <$%02X",		handler = inc_zpg},
	0xE7 = {mnemonic = "isc zpg",	format = "isc <$%02X",		handler = isc_zpg},
	0xE8 = {mnemonic = "inx",									handler = inx},
	0xE9 = {mnemonic = "sbc #",		format = "sbc #$%02X",		handler = sbc_imm},
	0xEA = {mnemonic = "nop",									handler = nop},
	0xEB = {mnemonic = "usbc #",	format = "usbc #$%02X",		handler = usbc},
	0xEC = {mnemonic = "cpx abs",	format = "cpx $%02X%02X",	handler = cpx_abs},
	0xED = {mnemonic = "sbc abs",	format = "sbc $%02X%02X",	handler = sbc_abs},
	0xEE = {mnemonic = "inc abs",	format = "inc $%02X%02X",	handler = inc_abs},
	0xEF = {mnemonic = "isc abs",	format = "isc $%02X%02X",	handler = isc_abs},
	0xF0 = {mnemonic = "beq",		format = "beq $%04X",		handler = beq},
	0xF1 = {mnemonic = "sbc ind,Y",	format = "sbc ($%02X),Y",	handler = sbc_indy},
	0xF2 = {mnemonic = "jam",									handler = jam},
	0xF3 = {mnemonic = "isc ind,Y",	format = "isc ($%02X),Y",	handler = isc_indy},
	0xF4 = {mnemonic = "nop zpg,X",	format = "nop <$%02X,X",	handler = nop_zpgx},
	0xF5 = {mnemonic = "sbc zpg,X",	format = "sbc <$%02X,X",	handler = sbc_zpgx},
	0xF6 = {mnemonic = "inc zpg,X",	format = "inc <$%02X,X",	handler = inc_zpgx},
	0xF7 = {mnemonic = "isc zpg,X",	format = "isc <$%02X,X",	handler = isc_zpgx},
	0xF8 = {mnemonic = "sed",									handler = sed},
	0xF9 = {mnemonic = "sbc abs,Y",	format = "sbc $%02X%02X,Y",	handler = sbc_absy},
	0xFA = {mnemonic = "nop imp",								handler = nop_implied},
	0xFB = {mnemonic = "isc abs,Y",	format = "isc $%02X%02X,Y",	handler = isc_absy},
	0xFC = {mnemonic = "nop abs,X",	format = "nop $%02X%02X,X",	handler = nop_absx},
	0xFD = {mnemonic = "sbc abs,X",	format = "sbc $%02X%02X,X",	handler = sbc_absx},
	0xFE = {mnemonic = "inc abs,X",	format = "inc $%02X%02X,X",	handler = inc_absx},
	0xFF = {mnemonic = "isc abs,X",	format = "isc $%02X%02X,X",	handler = isc_absx},
}
