package main

// Instruction decoding table
Instructions := [256]Instruction {
	0x00 = {mnemonic = "brk", handler = brk},
	0x01 = {mnemonic = "ora ind,X", handler = ora_indx},
	0x02 = {handler = not_implemented},
	0x03 = {handler = not_implemented},
	0x04 = {handler = not_implemented},
	0x05 = {mnemonic = "ora zpg", handler = ora_zpg},
	0x06 = {mnemonic = "asl zpg", handler = asl_zpg},
	0x07 = {handler = not_implemented},
	0x08 = {mnemonic = "php", handler = php},
	0x09 = {mnemonic = "ora #", handler = ora_imm},
	0x0A = {mnemonic = "asl A", handler = asl_a},
	0x0B = {handler = not_implemented},
	0x0C = {handler = not_implemented},
	0x0D = {mnemonic = "ora abs", handler = ora_abs},
	0x0E = {mnemonic = "asl abs", handler = asl_abs},
	0x0F = {handler = not_implemented},
	0x10 = {mnemonic = "bpl", handler = bpl},
	0x11 = {mnemonic = "ora ind,Y", handler = ora_indy},
	0x12 = {handler = not_implemented},
	0x13 = {handler = not_implemented},
	0x14 = {handler = not_implemented},
	0x15 = {mnemonic = "ora zpg,X", handler = ora_zpgx},
	0x16 = {mnemonic = "asl zpg,X", handler = asl_zpgx},
	0x17 = {handler = not_implemented},
	0x18 = {mnemonic = "clc", handler = clc},
	0x19 = {mnemonic = "ora abs,Y", handler = ora_absy},
	0x1A = {handler = not_implemented},
	0x1B = {handler = not_implemented},
	0x1C = {handler = not_implemented},
	0x1D = {mnemonic = "ora abs,X", handler = ora_absx},
	0x1E = {mnemonic = "asl abs,X", handler = asl_absx},
	0x1F = {handler = not_implemented},
	0x20 = {mnemonic = "jsr", handler = jsr},
	0x21 = {mnemonic = "and ind,X", handler = and_indx},
	0x22 = {handler = not_implemented},
	0x23 = {handler = not_implemented},
	0x24 = {mnemonic = "bit zpg", handler = bit_zpg},
	0x25 = {mnemonic = "and zpg", handler = and_zpg},
	0x26 = {mnemonic = "rol zpg", handler = rol_zpg},
	0x27 = {handler = not_implemented},
	0x28 = {mnemonic = "plp", handler = plp},
	0x29 = {mnemonic = "and #", handler = and_imm},
	0x2A = {mnemonic = "rol A", handler = rol_a},
	0x2B = {handler = not_implemented},
	0x2C = {mnemonic = "bit abs", handler = bit_abs},
	0x2D = {mnemonic = "and abs", handler = and_abs},
	0x2E = {mnemonic = "rol abs", handler = rol_abs},
	0x2F = {handler = not_implemented},
	0x30 = {mnemonic = "bmi", handler = bmi},
	0x31 = {mnemonic = "and ind,Y", handler = and_indy},
	0x32 = {handler = not_implemented},
	0x33 = {handler = not_implemented},
	0x34 = {handler = not_implemented},
	0x35 = {mnemonic = "and zpg,X", handler = and_zpgx},
	0x36 = {mnemonic = "rol zpg,X", handler = rol_zpgx},
	0x37 = {handler = not_implemented},
	0x38 = {mnemonic = "sec", handler = sec},
	0x39 = {mnemonic = "and abs,Y", handler = and_absy},
	0x3A = {handler = not_implemented},
	0x3B = {handler = not_implemented},
	0x3C = {handler = not_implemented},
	0x3D = {mnemonic = "and abs,X", handler = and_absx},
	0x3E = {mnemonic = "rol abs,X", handler = rol_absx},
	0x3F = {handler = not_implemented},
	0x40 = {mnemonic = "rti", handler = rti},
	0x41 = {mnemonic = "eor ind,X", handler = eor_indx},
	0x42 = {handler = not_implemented},
	0x43 = {handler = not_implemented},
	0x44 = {handler = not_implemented},
	0x45 = {mnemonic = "eor zpg", handler = eor_zpg},
	0x46 = {mnemonic = "lsr zpg", handler = lsr_zpg},
	0x47 = {handler = not_implemented},
	0x48 = {mnemonic = "pha", handler = pha},
	0x49 = {mnemonic = "eor #", handler = eor_imm},
	0x4A = {mnemonic = "lsr A", handler = lsr_a},
	0x4B = {handler = not_implemented},
	0x4C = {mnemonic = "jmp abs", handler = jmp_abs},
	0x4D = {mnemonic = "eor abs", handler = eor_abs},
	0x4E = {mnemonic = "lsr abs", handler = lsr_abs},
	0x4F = {handler = not_implemented},
	0x50 = {mnemonic = "bvc", handler = bvc},
	0x51 = {mnemonic = "eor ind,Y", handler = eor_indy},
	0x52 = {handler = not_implemented},
	0x53 = {handler = not_implemented},
	0x54 = {handler = not_implemented},
	0x55 = {mnemonic = "eor zpg,X", handler = eor_zpgx},
	0x56 = {mnemonic = "lsr zpg,X", handler = lsr_zpgx},
	0x57 = {handler = not_implemented},
	0x58 = {mnemonic = "cli", handler = cli},
	0x59 = {mnemonic = "eor abs,Y", handler = eor_absy},
	0x5A = {handler = not_implemented},
	0x5B = {handler = not_implemented},
	0x5C = {handler = not_implemented},
	0x5D = {mnemonic = "eor abs,X", handler = eor_absx},
	0x5E = {mnemonic = "lsr abs,X", handler = lsr_absx},
	0x5F = {handler = not_implemented},
	0x60 = {mnemonic = "rts", handler = rts},
	0x61 = {mnemonic = "adc ind,X", handler = adc_indx},
	0x62 = {handler = not_implemented},
	0x63 = {handler = not_implemented},
	0x64 = {handler = not_implemented},
	0x65 = {mnemonic = "adc zpg", handler = adc_zpg},
	0x66 = {mnemonic = "ror zpg", handler = ror_zpg},
	0x67 = {handler = not_implemented},
	0x68 = {mnemonic = "pla", handler = pla},
	0x69 = {mnemonic = "adc #", handler = adc_imm},
	0x6A = {mnemonic = "ror A", handler = ror_a},
	0x6B = {handler = not_implemented},
	0x6C = {mnemonic = "jmp ind", handler = jmp_ind},
	0x6D = {mnemonic = "adc abs", handler = adc_abs},
	0x6E = {mnemonic = "ror abs", handler = ror_abs},
	0x6F = {handler = not_implemented},
	0x70 = {mnemonic = "bvs", handler = bvs},
	0x71 = {mnemonic = "adc ind,Y", handler = adc_indy},
	0x72 = {handler = not_implemented},
	0x73 = {handler = not_implemented},
	0x74 = {handler = not_implemented},
	0x75 = {mnemonic = "adc zpg,X", handler = adc_zpgx},
	0x76 = {mnemonic = "ror zpg,X", handler = ror_zpgx},
	0x77 = {handler = not_implemented},
	0x78 = {mnemonic = "sei", handler = sei},
	0x79 = {mnemonic = "adc abs,Y", handler = adc_absy},
	0x7A = {handler = not_implemented},
	0x7B = {handler = not_implemented},
	0x7C = {handler = not_implemented},
	0x7D = {mnemonic = "adc abs,X", handler = adc_absx},
	0x7E = {mnemonic = "ror abs,X", handler = ror_absx},
	0x7F = {handler = not_implemented},
	0x80 = {handler = not_implemented},
	0x81 = {mnemonic = "sta ind,X", handler = sta_indx},
	0x82 = {handler = not_implemented},
	0x83 = {handler = not_implemented},
	0x84 = {mnemonic = "sty zpg", handler = sty_zpg},
	0x85 = {mnemonic = "sta zpg", handler = sta_zpg},
	0x86 = {mnemonic = "stx zpg", handler = stx_zpg},
	0x87 = {handler = not_implemented},
	0x88 = {mnemonic = "dey", handler = dey},
	0x89 = {handler = not_implemented},
	0x8A = {mnemonic = "txa", handler = txa},
	0x8B = {handler = not_implemented},
	0x8C = {mnemonic = "sty abs", handler = sty_abs},
	0x8D = {mnemonic = "sta abs", handler = sta_abs},
	0x8E = {mnemonic = "stx abs", handler = stx_abs},
	0x8F = {handler = not_implemented},
	0x90 = {mnemonic = "bcc", handler = bcc},
	0x91 = {mnemonic = "sta ind,Y", handler = sta_indy},
	0x92 = {handler = not_implemented},
	0x93 = {handler = not_implemented},
	0x94 = {mnemonic = "sty zpg,X", handler = sty_zpgx},
	0x95 = {mnemonic = "sta zpg,X", handler = sta_zpgx},
	0x96 = {mnemonic = "stx zpg,Y", handler = stx_zpgy},
	0x97 = {handler = not_implemented},
	0x98 = {mnemonic = "tya", handler = tya},
	0x99 = {mnemonic = "sta abs,Y", handler = sta_absy},
	0x9A = {mnemonic = "txs", handler = txs},
	0x9B = {handler = not_implemented},
	0x9C = {handler = not_implemented},
	0x9D = {mnemonic = "sta abs,X", handler = sta_absx},
	0x9E = {handler = not_implemented},
	0x9F = {handler = not_implemented},
	0xA0 = {mnemonic = "ldy #", handler = ldy_imm},
	0xA1 = {mnemonic = "lda ind,X", handler = lda_indx},
	0xA2 = {mnemonic = "ldx #", handler = ldx_imm},
	0xA3 = {handler = not_implemented},
	0xA4 = {mnemonic = "ldy zpg", handler = ldy_zpg},
	0xA5 = {mnemonic = "lda zpg", handler = lda_zpg},
	0xA6 = {mnemonic = "ldx zpg", handler = ldx_zpg},
	0xA7 = {handler = not_implemented},
	0xA8 = {mnemonic = "tay", handler = tay},
	0xA9 = {mnemonic = "lda #", handler = lda_imm},
	0xAA = {mnemonic = "tax", handler = tax},
	0xAB = {handler = not_implemented},
	0xAC = {mnemonic = "ldy abs", handler = ldy_abs},
	0xAD = {mnemonic = "lda abs", handler = lda_abs},
	0xAE = {mnemonic = "ldx abs", handler = ldx_abs},
	0xAF = {handler = not_implemented},
	0xB0 = {mnemonic = "bcs", handler = bcs},
	0xB1 = {mnemonic = "lda ind,Y", handler = lda_indy},
	0xB2 = {handler = not_implemented},
	0xB3 = {handler = not_implemented},
	0xB4 = {mnemonic = "ldy zpg,X", handler = ldy_zpgx},
	0xB5 = {mnemonic = "lda zpg,X", handler = lda_zpgx},
	0xB6 = {mnemonic = "ldx zpg,Y", handler = ldx_zpgy},
	0xB7 = {handler = not_implemented},
	0xB8 = {mnemonic = "clv", handler = clv},
	0xB9 = {mnemonic = "lda abs,Y", handler = lda_absy},
	0xBA = {mnemonic = "tsx", handler = tsx},
	0xBB = {handler = not_implemented},
	0xBC = {mnemonic = "ldy abs,X", handler = ldy_absx},
	0xBD = {mnemonic = "lda abs,X", handler = lda_absx},
	0xBE = {mnemonic = "ldx abs,Y", handler = ldx_absy},
	0xBF = {handler = not_implemented},
	0xC0 = {mnemonic = "cpy imm", handler = cpy_imm},
	0xC1 = {mnemonic = "cmp ind,X", handler = cmp_indx},
	0xC2 = {handler = not_implemented},
	0xC3 = {handler = not_implemented},
	0xC4 = {mnemonic = "cpy zpg", handler = cpy_zpg},
	0xC5 = {mnemonic = "cmp zpg", handler = cmp_zpg},
	0xC6 = {mnemonic = "dec zpg", handler = dec_zpg},
	0xC7 = {handler = not_implemented},
	0xC8 = {mnemonic = "iny", handler = iny},
	0xC9 = {mnemonic = "cmp #", handler = cmp_imm},
	0xCA = {mnemonic = "dex", handler = dex},
	0xCB = {handler = not_implemented},
	0xCC = {mnemonic = "cpy abs", handler = cpy_abs},
	0xCD = {mnemonic = "cmp abs", handler = cmp_abs},
	0xCE = {mnemonic = "dec abs", handler = dec_abs},
	0xCF = {handler = not_implemented},
	0xD0 = {mnemonic = "bne", handler = bne},
	0xD1 = {mnemonic = "cmp ind,Y", handler = cmp_indy},
	0xD2 = {handler = not_implemented},
	0xD3 = {handler = not_implemented},
	0xD4 = {handler = not_implemented},
	0xD5 = {mnemonic = "cmp zpg,X", handler = cmp_zpgx},
	0xD6 = {mnemonic = "dec zpg,X", handler = dec_zpgx},
	0xD7 = {handler = not_implemented},
	0xD8 = {mnemonic = "cld", handler = cld},
	0xD9 = {mnemonic = "cmp abs,Y", handler = cmp_absy},
	0xDA = {handler = not_implemented},
	0xDB = {handler = not_implemented},
	0xDC = {handler = not_implemented},
	0xDD = {mnemonic = "cmp abs,X", handler = cmp_absx},
	0xDE = {mnemonic = "dec abs,X", handler = dec_absx},
	0xDF = {handler = not_implemented},
	0xE0 = {mnemonic = "cpx imm", handler = cpx_imm},
	0xE1 = {mnemonic = "sbc ind,X", handler = sbc_indx},
	0xE2 = {handler = not_implemented},
	0xE3 = {handler = not_implemented},
	0xE4 = {mnemonic = "cpx zpg", handler = cpx_zpg},
	0xE5 = {mnemonic = "sbc zpg", handler = sbc_zpg},
	0xE6 = {mnemonic = "inc zpg", handler = inc_zpg},
	0xE7 = {handler = not_implemented},
	0xE8 = {mnemonic = "inx", handler = inx},
	0xE9 = {mnemonic = "sbc #", handler = sbc_imm},
	0xEA = {mnemonic = "nop", handler = nop},
	0xEB = {handler = not_implemented},
	0xEC = {mnemonic = "cpx abs", handler = cpx_abs},
	0xED = {mnemonic = "sbc abs", handler = sbc_abs},
	0xEE = {mnemonic = "inc abs", handler = inc_abs},
	0xEF = {handler = not_implemented},
	0xF0 = {mnemonic = "beq", handler = beq},
	0xF1 = {mnemonic = "sbc ind,Y", handler = sbc_indy},
	0xF2 = {handler = not_implemented},
	0xF3 = {handler = not_implemented},
	0xF4 = {handler = not_implemented},
	0xF5 = {mnemonic = "sbc zpg,X", handler = sbc_zpgx},
	0xF6 = {mnemonic = "inc zpg,X", handler = inc_zpgx},
	0xF7 = {handler = not_implemented},
	0xF8 = {mnemonic = "sed", handler = sed},
	0xF9 = {mnemonic = "sbc abs,Y", handler = sbc_absy},
	0xFA = {handler = not_implemented},
	0xFB = {handler = not_implemented},
	0xFC = {handler = not_implemented},
	0xFD = {mnemonic = "sbc abs,X", handler = sbc_absx},
	0xFE = {mnemonic = "inc abs,X", handler = inc_absx},
	0xFF = {handler = not_implemented},
}